Repository carvel-dev/secretgen-controller, pull requests merged in 2022-11, with the labels that each got.

#112 [v0.11.x] Update vendored modules to address HIGH/CRITICAL CVEs
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/modules.txt
Labels: cla-not-required, v0.11.x

#111 Add dependabot for supported lines
  .github/dependabot.yml
Labels: cla-not-required

#133 Port base OS image change from photon to scratch
  Dockerfile
Labels: cla-not-required, v0.9.x

#152 Bump Golang to 1.19.3
  .github/workflows/golangci-lint.yml
  .github/workflows/kind-action.yml
  .github/workflows/release.yml
  .github/workflows/test-gh.yml
  .github/workflows/trivy-scan.yml
  Dockerfile
  pkg/satoken/token_manager.go
  pkg/tracker/tracker.go
Labels: cla-not-required

#150 Introduce inclusive naming check and update existing language
  .github/workflows/inclusive-language-check.yml
  .wokeignore
Labels: cla-not-required

#161 Bump GoLang to v1.19.3
  .github/workflows/golangci-lint.yml
  .github/workflows/kind-action.yml
  .github/workflows/test-gh.yml
  .github/workflows/trivy-scan.yml
  .golangci.yml
  Dockerfile
  go.mod
  go.sum
  pkg/satoken/token_manager.go
  pkg/tracker/tracker.go
Labels: v0.9.x

#159 Bump Golang to v1.19.3
  .github/workflows/golangci-lint.yml
  .github/workflows/kind-action.yml
  .github/workflows/test-gh.yml
  .github/workflows/trivy-scan.yml
  .golangci.yml
  Dockerfile
  go.mod
  pkg/satoken/token_manager.go
  pkg/tracker/tracker.go
Labels: cla-not-required, v0.11.x
